### ISSUE TITLE
Have instructions for potential GMT distribution and data server mirrors

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/website#21]
Seems we should have instructions on our website for potential GMT distribution and data server mirrors.  There should one mirror script for an ftp server (to serve the GMT installers) [could just server the latest [< 1 Gb] or the entire history of releases [15 Gb], and one mirror script for a data server[50+ Gb].

_Originally posted by @PaulWessel in https://github.com/GenericMappingTools/gmt/issues/1675#issuecomment-536338053_

**Comment by PaulWessel** [comment]
It seems the simplest way to mirror the GMT ftp site is to use [lftp](lftp.yar.ru).  It is available in all distros. I tested it for syncing the gmt ftp to my computer at home this way:

`lftp -e "mirror --delete --parallel=8 gmt gmt; bye" ftp.soest.hawaii.edu
`

which places the remove gmt directory in the current directory.  Presumably one would run this via crontab once a day and specify a local hard path to where the gmt directory should be mirrored.  May need to follow with a `chmod -R og+r gmt` depending on local umask - I could not get it to inherit exact permissions otherwise.  The number of parallel downloads is optional can may need to be tuned for each location.

**Comment by PaulWessel** [comment]
Hi @seisman, since you (?) are operating that http mirror in China, perhaps we can take that mirroring script and generalize it and make a description of how to mirror via ftp (use lftp) or http (your script)?

**Comment by seisman** [comment]
The USTC LUG is the one operating the GMT mirror. I recall that they had trouble mirror the UH ftp site, and decided to mirror the mirror gmt.mirror.ac.za/gmt. I'll contact them for more information about their mirroring script. 

[This site](https://ctan.org/mirrors/register/) gives instruction to mirror the CTAN site, which may be useful to us.

**Comment by seisman** [comment]
The USTC mirror uses following command to mirror the ac.za site:
```
rsync -av --delete rsync://gmt.mirror.ac.za/gmt local-gmt-dir
```

But it doesn't work for the UH mirror:
```
rsync -av --delete rsync://ftp.soest.hawaii.edu/gmt local-gmt-dir   
rsync: failed to connect to ftp.soest.hawaii.edu: Connection refused (61)
rsync error: error in socket IO (code 10) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/clientserver.c(106) [receiver=2.6.9]
```
